import React from 'react';
import {
  Menu,
  HardHat,
  LayoutDashboard,
  Lock,
  Unlock,
  Users,
  BarChart3,
  X,
  Clock,
  History,
  Fingerprint,
  KeyRound,
  Camera,
  IdCard,
  UserPlus,
  Edit,
  Trash2,
  Calendar,
  ArrowRight,
  ArrowLeft,
  Smartphone,
  Monitor,
  Tablet,
  ShoppingBag,
  ShoppingCart,
  Package,
  User,
  Banknote,
  Scale,
  ShieldAlert,
  Printer,
  FileDown,
  PlaneTakeoff,
  Archive,
  FileText,
  CheckCircle,
  Home,
  Kanban,
  Bell,
  Settings,
  UserCheck,
  Activity,
  LayoutTemplate,
  RefreshCw,
  HelpCircle,
  QrCode,
  Scan,
  Filter,
  Plus,
  Send,
  Paperclip,
  AlertTriangle,
  Check,
  Search,
  Mail,
  Info,
  ExternalLink,
  Shield,
  CheckSquare,
  XCircle,
  Eye,
  EyeOff,
  Truck,
  Folder,
  Upload,
  Image as ImageIcon,
  Building,
  Sliders,
  Flag,
  Download,
  Copy,
  Share2
} from 'lucide-react';

interface IconProps {
  name: string;
  size?: number;
  className?: string;
  strokeWidth?: number;
}

export const Icon: React.FC<IconProps> = ({ name, size = 24, className = "", strokeWidth = 2 }) => {
  const iconMap: Record<string, React.ComponentType<any>> = {
    'menu': Menu,
    'hard-hat': HardHat,
    'layout-dashboard': LayoutDashboard,
    'lock': Lock,
    'unlock': Unlock,
    'users': Users,
    'bar-chart-3': BarChart3,
    'x': X,
    'clock': Clock,
    'history': History,
    'fingerprint': Fingerprint,
    'key-round': KeyRound,
    'camera': Camera,
    'id-card': IdCard,
    'user-plus': UserPlus,
    'edit-3': Edit,
    'trash': Trash2,
    'trash-2': Trash2,
    'calendar': Calendar,
    'arrow-right': ArrowRight,
    'arrow-left': ArrowLeft,
    'smartphone': Smartphone,
    'monitor': Monitor,
    'tablet': Tablet,
    'shopping-bag': ShoppingBag,
    'shopping-cart': ShoppingCart,
    'package': Package,
    'user': User,
    'banknote': Banknote,
    'scale': Scale,
    'shield-alert': ShieldAlert,
    'printer': Printer,
    'file-down': FileDown,
    'plane-takeoff': PlaneTakeoff,
    'archive': Archive,
    'file-text': FileText,
    'check-circle': CheckCircle,
    'home': Home,
    'kanban': Kanban,
    'bell': Bell,
    'settings': Settings,
    'user-check': UserCheck,
    'activity': Activity,
    'layout-template': LayoutTemplate,
    'refresh-cw': RefreshCw,
    'qr-code': QrCode,
    'scan': Scan,
    'filter': Filter,
    'plus': Plus,
    'send': Send,
    'paperclip': Paperclip,
    'alert-triangle': AlertTriangle,
    'check': Check,
    'search': Search,
    'mail': Mail,
    'info': Info,
    'external-link': ExternalLink,
    'shield': Shield,
    'check-square': CheckSquare,
    'x-circle': XCircle,
    'eye': Eye,
    'eye-off': EyeOff,
    'truck': Truck,
    'folder': Folder,
    'upload': Upload,
    'image': ImageIcon,
    'building': Building,
    'sliders': Sliders,
    'flag': Flag,
    'download': Download,
    'copy': Copy,
    'share': Share2
  };

  const LucideIcon = iconMap[name] || HelpCircle;
  return <LucideIcon size={size} className={className} strokeWidth={strokeWidth} />;
};
